### PR TITLE
feat: add GuardDuty organization features

### PR DESCRIPTION
**Pull request by darrenl33**
## what

- Enable and configure new GuardDuty features across member AWS accounts
- GuardDuty API changes in March 2023, new features are only available with the features object
- Add GuardDuty terraform resource, `aws_guardduty_organization_configuration_feature`

## why

- Add support for new GuardDuty protection features

## references

- https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-feature-object-api-changes-march2023.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/guardduty_organization_configuration_feature

### CODE REVIEW

**Review by RoseSecurity — COMMENTED** [review]
I am a really big fan of these features and would like to see them incorporated. Once we iron out some of the structure, I am excited to see this addition!

**Comment by goruha** [comment]
@darrenl33 Thanks for your contribution.
This feature is handy. 
At the same time, I agree with @RoseSecurity that the inputs are confusing. 
But I think we can do even better

```terraform
variable "guardduty_features" {
  type = map(object({
      auto_enable  = optional(string, "NONE")
      additional_configuration = optional(map(object({
         auto_enable  = optional(string, "None")
      })), {})
    })
  }))

  validation {
    condition           = alltrue([ for k in keys(var.guardduty_features) : contains(["S3_DATA_EVENTS", "EKS_AUDIT_LOGS", "EBS_MALWARE_PROTECTION", "RDS_LOGIN_EVENTS", "EKS_RUNTIME_MONITORING", "LAMBDA_NETWORK_LOGS", "RUNTIME_MONITORING"],  k) ])
    error_message = "Guardduty features can but only one of [\"S3_DATA_EVENTS\", \"EKS_AUDIT_LOGS\", \"EBS_MALWARE_PROTECTION\", \"RDS_LOGIN_EVENTS\", \"EKS_RUNTIME_MONITORING\", \"LAMBDA_NETWORK_LOGS\", \"RUNTIME_MONITORING\"]"
  }

  validation {
    condition           =  ! (contains(keys(var.guardduty_features), "EKS_RUNTIME_MONITORING") &&  contains(keys(var.guardduty_features), "RUNTIME_MONITORING"))
    error_message = "Only one of two features \"EKS_RUNTIME_MONITORING\" or \"RUNTIME_MONITORING\" can be added"
  }

  validation {
    condition           =  alltrue([ for k, v in var.guardduty_features :  length(v.additional_configuration) == 0 if !contains(["EKS_RUNTIME_MONITORING", "RUNTIME_MONITORING"], k) ])
    error_message = "Additional feature configuration block allowed only for features \"EKS_RUNTIME_MONITORING\" or \"RUNTIME_MONITORING\""
  }

  validation {
    condition           =  alltrue([ for k, v in var.guardduty_features :  contains(["NEW", "ALL", "NONE"], v.auto_enable)
    error_message = "Auto enabled valid values are \"NEW\", \"ALL\", \"NONE\""
  }

  validation {
    condition           =  alltrue([ for k, v in var.guardduty_features :  length(v.additional_configuration) == 0 if !contains(["EKS_RUNTIME_MONITORING", "RUNTIME_MONITORING"], k) ])
    error_message = "Additional feature configuration block allowed only for features \"EKS_RUNTIME_MONITORING\" or \"RUNTIME_MONITORING\""
  }


  default     = {}
  nullable    = false
}
```

**Review by goruha — CHANGES_REQUESTED** [review]
See the comments ^

**Comment by darrenl33** [comment]
closing this to test, I'll open a new one after the code freeze. thanks for the comments!

**Pull request closed without merging**
